### ISSUE TITLE
PHP Fatal error:  Declaration of Arkounay\Bundle\QuickAdminGeneratorBundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder

### ISSUE THREAD

**Issue by j0r1s** [Arkounay/QuickAdminGeneratorBundle#21]
Hello !

I wanted to try this bundle out, but I'm getting this error on cache clear after install : 
SF 7.0.5

```
PHP Fatal error:  Declaration of Arkounay\Bundle\QuickAdminGeneratorBundle\DependencyInjection\Configuration::getConfigTreeBuilder() must be compatible with Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder(): Symfony\Component\Config\Definition\Builder\TreeBuilder
``` 

`getConfigTreeBuilder`  should return a `TreeBuilder` object, I can make a PR if needed.

**Comment by Arkounay** [comment]
Hello, this is probably because composer chose an older version for some reasons, latest version is `5.4.4` and the `TreeBuilder` return type was added in `3.0`, so `1.x` or `2.x` were probably installed.
It happened once for someone else too, not sure why
